project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_KEY
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /lib/l10n/intl_en.arb
    translation: /lib/l10n/intl_%locale%.arb
    type: arb
    update_option: update_as_unapproved
bundles:
  - 6
