import 'package:flutter/widgets.dart';

/// Returns the localized Misskey title for a known achievement.
///
/// The identifier is returned unchanged when a newer server sends an
/// achievement that this client does not know yet.
String achievementTitle(BuildContext context, String? identifier) {
  if (identifier == null || identifier.isEmpty) {
    return '-';
  }
  final index = _achievementIds.indexOf(identifier);
  if (index < 0) {
    return identifier;
  }

  final locale = Localizations.localeOf(context);
  if (locale.languageCode == 'ja') {
    return _jaTitles[index];
  }
  if (locale.languageCode == 'zh') {
    return locale.countryCode == 'TW'
        ? _traditionalChineseTitles[index]
        : _simplifiedChineseTitles[index];
  }
  return _englishTitles[index];
}

const _achievementIds = <String>[
  'notes1',
  'notes10',
  'notes100',
  'notes500',
  'notes1000',
  'notes5000',
  'notes10000',
  'notes20000',
  'notes30000',
  'notes40000',
  'notes50000',
  'notes60000',
  'notes70000',
  'notes80000',
  'notes90000',
  'notes100000',
  'login3',
  'login7',
  'login15',
  'login30',
  'login60',
  'login100',
  'login200',
  'login300',
  'login400',
  'login500',
  'login600',
  'login700',
  'login800',
  'login900',
  'login1000',
  'noteClipped1',
  'noteFavorited1',
  'myNoteFavorited1',
  'profileFilled',
  'markedAsCat',
  'following1',
  'following10',
  'following50',
  'following100',
  'following300',
  'followers1',
  'followers10',
  'followers50',
  'followers100',
  'followers300',
  'followers500',
  'followers1000',
  'collectAchievements30',
  'viewAchievements3min',
  'iLoveMisskey',
  'foundTreasure',
  'client30min',
  'client60min',
  'noteDeletedWithin1min',
  'postedAtLateNight',
  'postedAt0min0sec',
  'selfQuote',
  'htl20npm',
  'viewInstanceChart',
  'outputHelloWorldOnScratchpad',
  'open3windows',
  'driveFolderCircularReference',
  'reactWithoutRead',
  'clickedClickHere',
  'justPlainLucky',
  'setNameToSyuilo',
  'passedSinceAccountCreated1',
  'passedSinceAccountCreated2',
  'passedSinceAccountCreated3',
  'loggedInOnBirthday',
  'loggedInOnNewYearsDay',
  'cookieClicked',
  'brainDiver',
  'smashTestNotificationButton',
  'tutorialCompleted',
  'bubbleGameExplodingHead',
  'bubbleGameDoubleExplodingHead',
];

const _englishTitles = <String>[
  'just setting up my msky',
  'Some notes',
  'A lot of notes',
  'Covered in notes',
  'A mountain of notes',
  'Overflowing notes',
  'Supernote',
  'Need... more... notes...',
  'Notes notes notes!',
  'Note factory',
  'Planet of notes',
  'Note quasar',
  'Note black hole',
  'Note galaxy',
  'Note universe',
  'ALL YOUR NOTE ARE BELONG TO US',
  'Beginner I',
  'Beginner II',
  'Beginner III',
  'Misskist I',
  'Misskist II',
  'Misskist III',
  'Regular I',
  'Regular II',
  'Regular III',
  'Expert I',
  'Expert II',
  'Expert III',
  'Master of Notes I',
  'Master of Notes II',
  'Master of Notes III',
  'Must... clip...',
  'Stargazer',
  'Seeking Stars',
  'Well-prepared',
  'I Am a Cat',
  'Following your first user',
  'Keep up... keep up...',
  'Lots of friends',
  '100 Friends',
  'Friend overload',
  'First follower',
  'Follow me!',
  'Coming in crowds',
  'Popular',
  'Please form a single line',
  'Radio Tower',
  'Influencer',
  'Achievement Collector',
  'Likes Achievements',
  'I Love Misskey',
  'Treasure Hunt',
  'Short break',
  'No "Miss" in Misskey',
  'Nevermind',
  'Nocturnal',
  'Speaking Clock',
  'Self-Reference',
  'Flowing Timeline',
  'Analyst',
  'Hello, world!',
  'Multi-Window',
  'Circular Reference',
  'Did you really read that?',
  'Click here',
  'Just Plain Lucky',
  'God Complex',
  'One Year Anniversary',
  'Two Year Anniversary',
  'Three Year Anniversary',
  'Happy Birthday',
  'Happy New Year!',
  'A game in which you click cookies',
  'Brain Diver',
  'Test overflow',
  'Misskey Elementary Course Diploma',
  '🤯',
  'Double🤯',
];

const _simplifiedChineseTitles = <String>[
  '初来乍到',
  '一些帖子',
  '很多帖子',
  '满是帖子',
  '积帖成山',
  '帖如泉涌',
  '超级帖',
  '还想要更多帖子',
  '帖子帖子帖子',
  '帖子工厂',
  '帖子星球',
  '帖子类星体',
  '帖子黑洞',
  '帖子星系',
  '帖子起源',
  'ALL YOUR NOTE ARE BELONG TO US',
  '初学者 I',
  '初学者 II',
  '初学者 III',
  'Misskist Ⅰ',
  'Misskist Ⅱ',
  'Misskist Ⅲ',
  '定期联系Ⅰ',
  '定期联系Ⅱ',
  '定期联系Ⅲ',
  '老熟人Ⅰ',
  '老熟人Ⅱ',
  '老熟人Ⅲ',
  '帖子大师 Ⅰ',
  '帖子大师 Ⅱ',
  '帖子大师 Ⅲ',
  '忍不住想加入便签',
  '观星者',
  '想要星星',
  '整装待发',
  '我是猫',
  '首次关注',
  '关注，跟随',
  '我的朋友很多',
  '胜友如云',
  '朋友成群',
  '最初的关注者',
  '关注我吧！',
  '三五成群',
  '胜友如云',
  '排列成行',
  '信号塔',
  '大影响家',
  '成就收藏家',
  '成就爱好者',
  'I Love Misskey',
  '寻宝',
  '休息一下！',
  'Misskey 重度依赖',
  '欲言又止',
  '夜猫子',
  '报时',
  '自我引用',
  '流动的时间线',
  '分析师',
  'Hello, world!',
  '多窗口',
  '循环引用',
  '有好好读过吗？',
  '点这里',
  '超高校级的幸运',
  '上帝情结',
  '一周年',
  '二周年',
  '三周年',
  '生日快乐',
  '恭贺新禧',
  '饼干点点乐',
  'Brain Diver',
  '过度测试',
  'Misskey 初学者课程 结业证书',
  '🤯',
  '两个🤯',
];

const _traditionalChineseTitles = <String>[
  '歡迎！',
  '若干貼文',
  '許多貼文',
  '滿滿的貼文',
  '堆積如山的貼文',
  '滔滔不絕的貼文',
  '超級貼文',
  '需要更多貼文',
  '貼文貼文貼文',
  '貼文工廠',
  '貼文星球',
  '貼文類星體',
  '貼文黑洞',
  '貼文銀河',
  '貼文宇宙',
  'ALL YOUR NOTE ARE BELONG TO US',
  '初學者Ⅰ',
  '初學者ⅠⅠ',
  '初學者ⅠⅠⅠ',
  'Misskist Ⅰ',
  'Misskist ⅠⅠ',
  'Misskist ⅠⅠⅠ',
  '普通Ⅰ',
  '普通ⅠⅠ',
  '普通ⅠⅠⅠ',
  '老兵Ⅰ',
  '老兵ⅠⅠ',
  '老兵ⅠⅠⅠ',
  '貼文大師Ⅰ',
  '貼文大師ⅠⅠ',
  '貼文大師ⅠⅠⅠ',
  '忍不住要收進摘錄裡',
  '觀星者',
  '想要星星',
  '有備而來',
  '我是貓',
  '首次追隨',
  '跟著跟著',
  '朋友很多',
  '一百位朋友',
  '朋友太多',
  '第一個追隨者',
  '追隨我吧！',
  '成群結隊',
  '熱門人物',
  '請排隊',
  '基地臺',
  '星光熠熠',
  '成就收藏家',
  '成就發燒友',
  'I Love Misskey',
  '尋寶',
  '休息一下',
  'Misskey 看太多',
  '欲言又止',
  '夜貓子',
  '報時',
  '自我引用',
  '源源不絕',
  '分析師',
  'Hello, world!',
  '多重視窗',
  '循環引用',
  '有好好讀過嗎？',
  '點擊這裡',
  '只是運氣好',
  '神與您同在',
  '一週年',
  '二週年',
  '三週年',
  '生日快樂',
  '新年快樂',
  '點擊餅乾的遊戲',
  'Brain Driver',
  '過度測試',
  'Misskey新手講座 結業證書',
  '🤯',
  '雙重🤯',
];

const _jaTitles = <String>[
  'just setting up my msky',
  'いくつかのノート',
  'たくさんのノート',
  'ノートまみれ',
  'ノートの山',
  '湧き出るノート',
  'スーパーノート',
  'ニードモアノート',
  'ノートノートノート',
  'ノート工場',
  'ノートの惑星',
  'ノートクエーサー',
  'ブラックノートホール',
  'ノートギャラクシー',
  'ノートバース',
  'ALL YOUR NOTE ARE BELONG TO US',
  'ビギナーⅠ',
  'ビギナーⅡ',
  'ビギナーⅢ',
  'ミスキストⅠ',
  'ミスキストⅡ',
  'ミスキストⅢ',
  '常連Ⅰ',
  '常連Ⅱ',
  '常連Ⅲ',
  'ベテランⅠ',
  'ベテランⅡ',
  'ベテランⅢ',
  'ノートマスターⅠ',
  'ノートマスターⅡ',
  'ノートマスターⅢ',
  'クリップせずにはいられないな',
  '星をみるひと',
  '星が欲しい',
  '準備万端',
  '吾輩は猫である',
  'はじめてのフォロー',
  'ついてく、ついてく',
  '友達たくさん',
  '友達100人',
  '友達過多',
  'はじめてのフォロワー',
  'フォローミー！',
  'ぞろぞろ',
  '人気者',
  '一列でお並びください',
  '基地局',
  'インフルエンサー',
  '実績コレクター',
  '実績好き',
  'I Love Misskey',
  '宝探し',
  'ひとやすみ',
  'Misskeyの見すぎ',
  'いまのなし',
  '夜行性',
  '時報',
  '自己言及',
  '流れるTL',
  'アナリスト',
  'Hello, world!',
  'マルチウィンドウ',
  '循環参照',
  'ちゃんと読んだ？',
  'ここをクリック',
  '単なるラッキー',
  '神様コンプレックス',
  '一周年',
  '二周年',
  '三周年',
  'ハッピーバースデー',
  'あけましておめでとうございます',
  'クッキーをクリックするゲーム',
  'Brain Diver',
  'テスト過剰',
  'Misskey初心者講座 修了証',
  '🤯',
  'ダブル🤯',
];
